/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package JSci.maths.symbolic;

interface ExpressionParserConstants {

  int EOF = 0;
  int ONEARGFUNCTION = 11;
  int PI = 12;
  int IUNIT = 13;
  int IDENTIFIER = 14;
  int LETTER = 15;
  int DIGIT = 16;
  int INUM = 17;
  int DNUM = 18;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "<ONEARGFUNCTION>",
    "\"pi\"",
    "\"i\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INUM>",
    "<DNUM>",
  };

}
